{{ if .Values.service.postgres }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.resourcePrefix }}postgres-pv-claim
  labels:
    app.service: {{ .Values.resourcePrefix }}postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
{{ end }}
