apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.prefix }}app-init
  annotations:
    helm.sh/hook: "post-install"
spec:
  template:
    spec:
      containers:
      - env:
        {{- range $key, $value := index .Values.docker.services "php-base" "environment" }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := .Values.docker.services.console.environment }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := .Values.environment }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        image: {{ .Values.docker.image.console }}
        imagePullPolicy: Always
        name: app-init
        command: ["app", "init"]
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory.app_init }}
          requests:
            memory: {{ .Values.resources.requests.memory.app_init }}
      imagePullSecrets:
      - name: {{ .Values.prefix }}docker-config
      restartPolicy: Never
