{{ if .Values.service.mysql }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.resourcePrefix }}mysql-pv-claim
  labels:
    app.service: {{ .Values.resourcePrefix }}mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
{{ end }}
