{{ if eq .Values.ingress "standard" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.service: {{ .Values.resourcePrefix }}nginx
  name: {{ .Values.resourcePrefix }}nginx
spec:
  rules:
  - host: {{ .Values.environment.APP_HOST }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.resourcePrefix }}nginx
          servicePort: 80
status:
  loadBalancer: {}
{{ end }}
