apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}console
  labels:
    app.service: {{ .Values.prefix }}console
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: {{ .Values.prefix }}console
  template:
    metadata:
      labels:
        app.service: {{ .Values.prefix }}console
    spec:
      containers:
      - env:
        {{ range $key, $value := .Values.environment }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{ end }}
        image: {{ .Values.docker.image.console }}
        imagePullPolicy: Always
        name: console
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory.console }}
          requests:
            memory: {{ .Values.resources.requests.memory.console }}
        readinessProbe:
          exec:
            command:
            - app
            - state
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        {{- if not (or (eq "" (include "application.volumeMounts.backend" .)) (eq "" (include "application.volumeMounts.all" .)) ) }}
        {{- include "application.volumeMounts.backend" . | indent 8 }}
        {{- include "application.volumeMounts.all" . | indent 8 }}
        {{- else }} []
        {{- end }}
      imagePullSecrets:
      - name: {{ .Values.prefix }}docker-config
      restartPolicy: Always
      volumes:
      {{- if not (or (eq "" (include "application.volumes.backend" .)) (eq "" (include "application.volumes.all" .)) ) }}
      {{- include "application.volumes.backend" . | indent 6 }}
      {{- include "application.volumes.all" . | indent 6 }}
      {{- else }} []
      {{- end }}
status: {}
