{{ if .Values.service.elasticsearch }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.resourcePrefix }}elasticsearch-pv-claim
  labels:
    app.service: {{ .Values.resourcePrefix }}elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{ end }}
