apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: {{ .Values.resourcePrefix }}php-fpm
  name: {{ .Values.resourcePrefix }}php-fpm
spec:
  ports:
  - name: tcp-9000
    port: 9000
    targetPort: 9000
  selector:
    app.service: {{ .Values.resourcePrefix }}php-fpm
status:
  loadBalancer: {}
